import { supabase } from './supabase';

export interface Report {
  id: string;
  title: string;
  type: string;
  date_range: string;
  format: string;
  status: 'pending' | 'ready' | 'failed';
  size_bytes: number;
  created_at: string;
}

export interface GenerateReportParams {
  type: string;
  date_range: string;
  format: string;
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export const reportService = {
  async getReports(): Promise<Report[]> {
    const { data, error } = await supabase
      .from('reports')
      .select('*')
      .order('created_at', { ascending: false });
    if (error) throw error;
    return data || [];
  },

  async generateReport(params: GenerateReportParams): Promise<Report> {
    const title = `${params.type} - ${params.date_range}`;
    // Insert as 'pending' first
    const { data: pending, error: insertErr } = await supabase
      .from('reports')
      .insert([{
        title,
        type: params.type,
        date_range: params.date_range,
        format: params.format,
        status: 'pending',
        size_bytes: 0,
      }])
      .select()
      .single();
    if (insertErr) throw insertErr;

    // Simulate generation (update to 'ready' with a size)
    const sizeBytes = Math.floor(Math.random() * 4500000) + 500000;
    const { data: ready, error: updateErr } = await supabase
      .from('reports')
      .update({ status: 'ready', size_bytes: sizeBytes })
      .eq('id', pending.id)
      .select()
      .single();
    if (updateErr) throw updateErr;
    return ready;
  },

  async deleteReport(id: string): Promise<void> {
    const { error } = await supabase
      .from('reports')
      .delete()
      .eq('id', id);
    if (error) throw error;
  },

  formatSize,

  downloadReport(report: Report): void {
    // Generate CSV-style content as a downloadable blob
    const content = [
      `ZOU NetMon Report`,
      `Title: ${report.title}`,
      `Type: ${report.type}`,
      `Date Range: ${report.date_range}`,
      `Format: ${report.format}`,
      `Generated: ${new Date(report.created_at).toLocaleString()}`,
      '',
      'This report was generated by ZOU NetMon Network Intelligence System',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.replace(/\s+/g, '_')}.${report.format.toLowerCase()}`;
    a.click();
    URL.revokeObjectURL(url);
  },

  subscribeToChanges(callback: () => void) {
    return supabase
      .channel('public:reports')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'reports' }, callback)
      .subscribe();
  },
};
