apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ict-netmon
      defaultBucket: network-metrics
      tlsSkipVerify: true
    secureJsonData:
      token: ict-super-secret-influx-token
    isDefault: true
    editable: true
