@version: 4.0

# Listen for UDP Syslog on port 5514 (Docker maps host:514 -> container:5514)
source s_routers {
    network(
        transport("udp")
        port(5514)
        flags(no-parse)
    );
};

# Store logs per source IP
destination d_router_files {
    file("/var/log/routers/${HOST}.log"
        owner("root") group("root") perm(0644)
        dir_perm(0755) create_dirs(yes)
    );
};

# Route logs
log {
    source(s_routers);
    destination(d_router_files);
};
